### ISSUE TITLE
Miantonomi Trails

### ISSUE THREAD

**Issue by SebastianKasan** [DigDigDig/Miantonomi_Trails#1]
Hello Steven, 

I just came across this repository in search for nice applications of qgis2threejs. Yours is very nice!

Could you explain to me,  how you made the plugin accept such high resolution imagery ?

Do I understand correctly, that if you want to do a similar project, you change the code directly or do you create the project in QGIS2threejs? I mean the customized menu an so on, do you do that for each project individually in the html file?

Thank you for your feedback...

Sebastian

**Comment by DigDigDig** [comment]
Hi Sebastian,

I used a 1m resolution LiDAR DEM as my base elevation and limited the project extent to a small area.  The entire area being displayed is only around 40 acres of land.  QGIS2threejs can be set to display a high resolution grid and texture, but this scales with the project extents.  This method has worked well for me, but I have found that the tool is of limted value if you are dealing with large geographic areas and are interested in fine details.

I'm happy to answer more specific questions if you have any.

[Data_Visualization_Poster_op.pdf](https://github.com/DigDigDig/Miantonomi_Trails/files/4214910/Data_Visualization_Poster_op.pdf)
